apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openclaw-admin.fullname" . }}-config
  labels:
    {{- include "openclaw-admin.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.env.config | nindent 2 }}
