apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openclaw-admin.fullname" . }}-secret
  labels:
    {{- include "openclaw-admin.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.env.secrets | nindent 2 }}
